server:
  port: 8100
  servlet:
    context-path: /api

spring:
  datasource:
    username: green
    password: Yi5582829.
    url: jdbc:mysql://127.0.0.1:3306/green?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #全局配置返回字符串
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

#showSql
logging:
  level:
    root: info
    top.green: info
#Druid
druid:
  loginUsername: root
  loginPassword: root

#和风天气
weather:
  key: fddfaceae56c427281671b3cb3ef732a

#身份认证
idCard:
  appCode: 6e164e7200b0418594a31cd5b2f48741